### ISSUE TITLE
关于单页面源码

### ISSUE THREAD

**Issue by sringly** [coderLMN/framework-free-single-page-app#2]
希望可以把完整的源代码放上来，谢谢

**Comment by coderLMN** [comment]
[gh-pages](https://github.com/coderLMN/framework-free-single-page-app/tree/gh-pages) 分支里就是演示的完整源代码，可以对照说明去看。

**Comment by sringly** [comment]
哦哦，没看到分支，谢谢。学习SPA单页的很好的demo

**Comment by coderLMN** [comment]
谢谢提醒，我把链接加到readme里面了
